spring.application.name=SpringBook

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_book
spring.datasource.username=springbook_api
spring.datasource.password=springbook123456789

spring.jpa.hibernate.ddl-auto=update
